kubectl delete -f backend-secret.yaml
kubectl delete -f backend-service.yaml
kubectl delete -f backend.yaml
kubectl delete -f frontend-configmap.yaml
kubectl delete -f frontend-service.yaml
kubectl delete -f frontend.yaml
kubectl delete -f ingress.yaml
kubectl delete -f mongodb-secret.yaml
kubectl delete -f mongodb-service.yaml
kubectl delete -f mongodb.yaml
kubectl delete -f mongodb-persistent-volume-claim.yaml
kubectl delete -f mongodb-persistent-volume.yaml
